### ISSUE TITLE
@chainlit/react-client is not compatible with 1.0.301

### ISSUE THREAD

**Issue by pfdm273** [Chainlit/chainlit#775]
Hi, 

thank you for your great work with chainlit. I just realized when upgrading to 1.0301 that the @chainlit/react-client library is no longer compatible:

```
 error TS2339: Property 'name' does not exist on type 'IThread'.
```

It would be great to release a new version. Maybe, as a feature request, it would be nice to release these client versions automatically?

**Comment by willydouhard** [comment]
Just published react-client `0.0.6` 🚀
