### PR TITLE
BUGFIX | SQLAlchemy - Fix show_input on chat resume

### PR DESCRIPTION
**Pull request by hayescode**
The [step attribute show_input](https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/step.py#L62) can be None, True/False, or the markdown syntax language. The code currently only handles `bool` not `str` so when resuming chats input is not displayed.

```py
showInput: Optional[Union[bool, str]]
```

I switched the if/then to only return None when it's None or "false" (data layer makes this a string)

### CODE REVIEW

**Comment by hayescode** [comment]
@willydouhard @dokterbob CI failed but not related to this PR. Can we ignore?

```bash
pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.
```

**Comment by dokterbob** [comment]
> @willydouhard @dokterbob CI failed but not related to this PR. Can we ignore?
> 
> ```shell
> pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.
> ```

@hayescode Please rebase to main, CI issues should be fixed!

**Comment by hayescode** [comment]
> > @willydouhard @dokterbob CI failed but not related to this PR. Can we ignore?
> > ```shell
> > pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.
> > ```
> 
> @hayescode Please rebase to main, CI issues should be fixed!

@dokterbob done and passed 😊thanks for fixing!

**Comment by dokterbob** [comment]
@hayescode To facilitate our work, any chance you could either provide a reference to equivalent code for other data backends or, alternatively, a test repo with project setup to replicate the issue + steps or, the gold standard, a regression test as part of your PR? 🙏🏼 🥺

**Comment by hayescode** [comment]
> @hayescode To facilitate our work, any chance you could either provide a reference to equivalent code for other data backends or, alternatively, a test repo with project setup to replicate the issue + steps or, the gold standard, a regression test as part of your PR? 🙏🏼 🥺

@dokterbob the other data backends are storing/retrieving this show_input differently than SQLAlchemy. This code change only affects chat_resume, the data is stored correctly in the database. Currently it only handles booleans but per the description there can also be strings for the markdown syntax used. I like your suggestion of adding tests here but since this is a relatively straightforward bugfix (code clearly only handles bool, not str) it might not be necessary here?

**Comment by hayescode** [comment]
@dokterbob I ran these tests connected to SQLAlchemyDataLayer and it works as expected. Can this be included in the next release?

```py
@cl.on_message
async def message(message_from_ui: cl.Message):
    json_step = cl.Step(name="json_step", show_input="json")
    json_step.input = "json"
    json_step.output = "json"
    await json_step.send()
    false_step = cl.Step(name="false_step", show_input=False)
    false_step.input = "false_step"
    false_step.output = "false_step"
    await false_step.send()
    true_step = cl.Step(name="true_step", show_input=True)
    true_step.input = "true_step"
    true_step.output = "true_step"
    await true_step.send()
    default_step = cl.Step(name="default_step")
    default_step.input = "default_step"
    default_step.output = "default_step"
    await default_step.send()
```

Database:
image


**Resume current-state** - Only "true" shows up when resuming chat
image

**Resume after bug fix in this PR**
image

**Comment by hayescode** [comment]
@dokterbob can this be merged for the 1.1.403 release in #1226?

**Comment by dokterbob** [comment]
> @dokterbob can this be merged for the 1.1.403 release next week?

Sorry I must have missed your message. I am afraid we are not going to be able to include it in the current release, but I'd be happy to ship it in the next -- preferably unit tested!

To provide better support for data layers, now _and_ in the future, I've been working on a refactor (#1288) which is ready for merge, but we've decide to ship as part of the next release. With this refactor in, I think we're ready to have unit tests for various data layers. 

I hugely appreciate your consistent contribution on this one and I think your work above would provide an excellent basis for a unit test in `backend/tests/data/test_sqlalchemy.py`. I can highly recommend you try and work with Claude 3.5 to write it (or user [aider-chat](https://pypi.org/project/aider-chat/), which is what I've done). 

What you can do _right now_ is merge https://github.com/Chainlit/chainlit/pull/1288 into your branch and start writing the unit tests (run them with `pytest` in the `backend` directory). Ideally, we'd have (at least) one test for each method -- but if you'd write just a test covering your issue here (`get_all_threads()`) I will accept it.

During the refactor, I did notice several `# type: ignore` statements and there were various statements which made [pyright](https://github.com/Microsoft/pyright) (#1244). Any patches resolving that are pure bonus points, as they are most likely bugs of some kind:
```
 error: Object of type "Session" cannot be used with "with" because it does not implement __aenter__
    Attribute "__aenter__" is unknown (reportGeneralTypeIssues)
  /Users/drbob/Development/chainlit/backend/chainlit/data/sql_alchemy.py:76:20 - error: Object of type "Session" cannot be used with "with" because it does not implement __aexit__ (reportGeneralTypeIssues)
  /Users/drbob/Development/chainlit/backend/chainlit/data/sql_alchemy.py:84:28 - error: Type "dict[Unknown, Unknown] | list[Unknown] | str | Unknown" is not assignable to return type "List[Dict[str, Any]] | int | None" (reportReturnType)
  /Users/drbob/Development/chainlit/backend/chainlit/data/sql_alchemy.py:579:31 - error: Argument of type "Any | None" cannot be assigned to parameter "input" of type "str" in function "__init__"
    Type "Any | None" is not assignable to type "str"
      "None" is not assignable to "str" (reportArgumentType)
 ```
 
In the longer run (ideally in the coming 2 releases), we want to hand over _all_ data layers to a shared community repo, directly maintained by the community. Curious to hear your thoughts on that. :)

**Comment by hayescode** [comment]
@dokterbob I think the overall vision of giving the community more control and influence on Chainlit is a good idea. I'd like to learn more about how each repo will maintain compatibility with each other and if Literal devs will adjust for breaking changes.

Regarding this PR and developing a bunch of unit tests, seems a little overkill for a 1 line bug fix. I feel this PR is very straightforward - show_input can either be strong/boolean but as you can see only boolean is handled.

You have a good vision for how this should work in an independent repo and once split there should be tests. But since we don't have tests covering this now, and as the pics show a bug, I ask that this PR gets merged here now.

**Review by dokterbob — APPROVED** [review]
